-- Base measure: the inforce logic
Inforce Premium = 
VAR _MinDate = MIN( dimCalendar[TheDate] )
VAR _MaxDate = MAX( dimCalendar[TheDate] )
RETURN
CALCULATE(
    SUM( factCLBOBBY[WRITTEN PREMIUM] ),
    factCLBOBBY[EFFECTIVE_DATE] <= _MaxDate,
    factCLBOBBY[POLICY END DATE] > _MinDate,
    REMOVEFILTERS( dimCalendar ),
    REMOVEFILTERS( unpivotSERVICERS )
)

-- Snapshot measure: forces single-date evaluation
Inforce Premium As Of Max Date = 
VAR _MaxDate = MAX( dimCalendar[TheDate] )
RETURN
CALCULATE(
    [Inforce Premium],
    FILTER(
        ALLSELECTED( dimCalendar ),
        dimCalendar[TheDate] = _MaxDate
    )
)
